View(mtcars)
plot(mtcars)
names(mtcars)
library(GGally)
ggpairs(mtcars)
library(ggplot2)
linep<-ggplot(data = mtcars,mapping = aes(mpg,hp))+geom_line(aes(color = gear))
print(linep)
bars<-ggplot(data = mtcars,mapping = aes(cyl))+geom_bar()
print(bars)
cyl<-ggplot(data = mtcars,mapping = aes(cyl))+geom_bar()
print(cyl)
vb<-ggplot(data = mtcars,mapping = aes(hp))+geom_density()
print(vb)
sd<-ggplot(data = mtcars,mapping = aes(mpg,hp))+geom_point()+geom_density_2d()
print(sd)
poing<-ggplot(data = mtcars,mapping = aes(mpg,hp))+geom_point(aes(color = gear))
print(poing)
mpli<-ggplot(data = mtcars,mapping = aes(disp,hp))+geom_line()+geom_point()
print(mpli)
